name: job_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  lottie: ^3.3.1
  connectivity_plus: ^6.1.4
  cached_network_image: ^3.4.1
  flutter_native_splash: ^2.4.6
  smooth_page_indicator: ^1.2.1

  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8

  # State Management
  get: ^4.7.2
  get_storage: ^2.1.1
  intl: ^0.20.2
  logger: ^2.6.0
  loading_animation_widget: ^1.3.0
  pinput: ^5.0.1
  image_picker: ^1.1.2
  carousel_slider: ^5.0.0
  dotted_line: ^3.2.3
  file_picker: ^10.3.1
  dotted_border: ^2.1.0
  flutter_pdfview: ^1.4.1+1

  # Security
  crypto: ^3.0.5

  # Performance Packages
  flutter_cache_manager: ^3.4.1
  shimmer: ^3.0.0

  # Firebase
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7
  firebase_storage: ^12.4.5
  http: ^1.4.0
  google_sign_in: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  #--------------- LOCAL ASSETS ------------------#
  assets:
    - assets/fonts/
    - assets/general/
    - assets/logo/
    - assets/social/
    - assets/lotties/
    - assets/companies/

  #--------------- LOCAL FONTS ------------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
    - family: KhmerOS
      fonts:
        - asset: assets/fonts/KhmerOS_siemreap.ttf
          weight: 400
