// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWLbC8wCtEfMM-N_fbrY2w3qAR_x-tnNo',
    appId: '1:341022674099:web:00e641ba7743d7a73474c6',
    messagingSenderId: '341022674099',
    projectId: 'laravel-ea7a9',
    authDomain: 'laravel-ea7a9.firebaseapp.com',
    storageBucket: 'laravel-ea7a9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1-7_04gC2Ya4vNJiQvoP-YPEJVy0nI2g',
    appId: '1:341022674099:android:ec0427af195d366e3474c6',
    messagingSenderId: '341022674099',
    projectId: 'laravel-ea7a9',
    storageBucket: 'laravel-ea7a9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAecXQ0AluaQYs1e-a_BTpeAfKRqZiJCbM',
    appId: '1:341022674099:ios:e038d2a98da30e2c3474c6',
    messagingSenderId: '341022674099',
    projectId: 'laravel-ea7a9',
    storageBucket: 'laravel-ea7a9.firebasestorage.app',
    androidClientId: '341022674099-1egfsvkfo2nqhsafler5tegkoifijg23.apps.googleusercontent.com',
    iosClientId: '341022674099-rr4a0v2c8f7fg129kooellm23cff1a3j.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizApp',
  );

}